// tailwind.config.js
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      'xs': '0px',
      'sm': '390px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1440px',
      '2xl': '1536px',
    },
    extend: {
      spacing: {
        '0': '0px',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '15px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '11': '44px',
        '12': '49px',
        '14': '56px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '28': '112px',
        '32': '122px',
        '36': '144px',
        '40': '160px',
        '44': '176px',
        '48': '192px',
        '52': '208px',
        '56': '224px',
        '60': '240px',
        '64': '256px',
        '72': '288px',
        '80': '320px',
        '96': '384px',
      },
      borderRadius: {
        '0': '0px',
        '2': '2px',
        '4': '4px',
        '5': '5px',
        '7': '7px',
        '10': '10px',
        'none': '0px',
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      colors: {
        primary: {
          DEFAULT: '#4E2FD2',
          light: '#6B4FE0',
          dark: '#3D25A8',
        },
        background: '#FFFFFF',
        paper: '#EDF4FF',
        surface: '#F8FAFF',
        text: {
          title: '#0B0D10',
          card: '#1F1F1F',
          secondary: '#6B7280',
          muted: '#9CA3AF',
        },
        accent: {
          green: '#0AA288',
          blue: '#4E2FD2',
        },
        border: {
          light: '#E5E7EB',
          medium: '#D1D5DB',
          dark: '#1F1F1F',
          varient: '#CCCCCC',
          selected: '#0AA288',
        },
        state: {
          selected: '#4E2FD2',
          selectedBg: '#F0EDFF',
          varientSelectedBg:'#1DF0BB0A',
          hover: '#F9FAFB',
        },
        discount: {
          bg: '#FEF3C7',
          text: '#92400E',
        },
        success: {
          bg: '#D1FAE5',
          text: '#065F46',
        },
      },
      fontFamily: {
        'gilroy': ['Gilroy', 'sans-serif'],
        'gilroy-medium': ['Gilroy-Medium', 'sans-serif'],
        'gilroy-semibold': ['Gilroy-SemiBold', 'sans-serif'],
        'gilroy-bold': ['Gilroy-Bold', 'sans-serif'],
      },
      fontSize: {
        'xs': ['10px', { lineHeight: '130%', letterSpacing: '0.6px' }],
        'sm': ['14px', { lineHeight: '140%', letterSpacing: '0.4px' }],
        'base': ['16px', { lineHeight: '150%', letterSpacing: '0px' }],
        'lg': ['18px', { lineHeight: '150%', letterSpacing: '0px' }],
        'xl': ['20px', { lineHeight: '140%', letterSpacing: '-0.2px' }],
        '2xl': ['24px', { lineHeight: '130%', letterSpacing: '-0.4px' }],
      },
      boxShadow: {
        'card': '0 2px 8px rgba(0, 0, 0, 0.06)',
        'card-hover': '0 4px 16px rgba(0, 0, 0, 0.1)',
        'review': '0 4px 20px rgba(0, 0, 0, 0.08)',
      },
      animation: {
        'slide-down': 'slideDown 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
      },
      keyframes: {
        slideDown: {
          '0%': { opacity: 0, transform: 'translateY(-10px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: 1, transform: 'translateY(0)' },
          '100%': { opacity: 0, transform: 'translateY(-10px)' },
        },
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
      },
    },
  },
  plugins: [],
}